default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
 
development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3
 
test:
  <<: *default
  database: myapp_test
 
production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
